#!/usr/bin/env python3
"""
Heuristic OS Variant Pool Generator
Orchestrates mutation, formal verification, and header packaging.
"""

import os
import subprocess
import hashlib
import json
import sys

# Configuration
MODULE_NAME = "worker_logic"
SOURCE_FILE = f"../projects/camkes/apps/hk_system/components/Worker/{MODULE_NAME}.c"
VARIANTS_COUNT = 5
ARTIFACTS_DIR = "build_artifacts"
OUTPUT_HEADER = "../projects/camkes/apps/hk_system/components/Repository/baked_mutations.h"

def run_command(cmd, description):
    print(f"[PROCESS] {description}...")
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] Command failed: {' '.join(cmd)}")
        print(f"[DETAILS] {e.stderr}")
        sys.exit(1)

def generate_variants():
    if not os.path.exists(ARTIFACTS_DIR):
        os.makedirs(ARTIFACTS_DIR)

    manifest = {"module_id": "hk_worker_core", "variants": []}

    # Step 1: Base LLVM IR Generation
    base_ir = os.path.join(ARTIFACTS_DIR, f"{MODULE_NAME}_base.ll")
    run_command([
        "clang-17", "-O1", "-S", "-emit-llvm", "-fno-discard-value-names",
        SOURCE_FILE, "-o", base_ir
    ], "Generating base LLVM IR")

    valid_count = 0
    attempts = 0

    while valid_count < VARIANTS_COUNT:
        attempts += 1
        mutated_ir = os.path.join(ARTIFACTS_DIR, f"{MODULE_NAME}_v{valid_count}.ll")
        
        # Step 2: Apply Mutation Pass
        # Note: Requires Mutator.so to be pre-built
        run_command([
            "opt-17", "-load-pass-plugin", "./Mutator.so", 
            "-passes=hk-mutate", "-S", base_ir, "-o", mutated_ir
        ], f"Applying mutation to variant {valid_count}")

        # Step 3: Formal Verification (Alive2)
        print(f"[VERIFY] Running formal equivalence check for variant {valid_count}...")
        alive_res = subprocess.run(["alive-tv", base_ir, mutated_ir], capture_output=True, text=True)

        if "Transformation seems to be correct!" in alive_res.stdout:
            print(f"[INFO] Variant {valid_count} verified successfully.")
            
            # Step 4: Binary Compilation (PIC)
            obj_file = os.path.join(ARTIFACTS_DIR, f"v{valid_count}.o")
            bin_file = os.path.join(ARTIFACTS_DIR, f"v{valid_count}.bin")
            
            run_command(["llc-17", "-relocation-model=pic", "-filetype=obj", mutated_ir, "-o", obj_file], "Compiling to object")
            run_command(["llvm-objcopy-17", "-O", "binary", "--only-section=.text", obj_file, bin_file], "Extracting text section")

            with open(bin_file, "rb") as f:
                data = f.read()
                file_hash = hashlib.sha256(data).hexdigest()

            manifest["variants"].append({
                "id": valid_count,
                "hash": file_hash,
                "size": len(data),
                "path": bin_file
            })
            valid_count += 1
        else:
            print(f"[WARN] Variant {valid_count} failed verification. Retrying...")

    return manifest

def package_header(manifest):
    print(f"[PACKAGE] Writing artifacts to {OUTPUT_HEADER}...")
    with open(OUTPUT_HEADER, "w") as f:
        f.write("/* Auto-generated by Heuristic OS Build System. DO NOT EDIT. */\n")
        f.write("#ifndef BAKED_MUTATIONS_H\n#define BAKED_MUTATIONS_H\n\n#include <stdint.h>\n\n")
        f.write(f"#define POOL_SIZE {len(manifest['variants'])}\n\n")

        for var in manifest["variants"]:
            f.write(f"/* Variant ID: {var['id']} | Hash: {var['hash']} */\n")
            f.write(f"static const uint8_t variant_{var['id']}_data[] = {{\n")
            with open(var['path'], "rb") as bf:
                hex_data = ", ".join([f"0x{b:02x}" for b in bf.read()])
                f.write(f"    {hex_data}\n")
            f.write("};\n\n")

        f.write("typedef struct {\n    int id;\n    const uint8_t* data;\n    int size;\n    const char* hash;\n} variant_record_t;\n\n")
        f.write("static const variant_record_t mutation_pool[POOL_SIZE] = {\n")
        for var in manifest["variants"]:
            f.write(f"    {{{var['id']}, variant_{var['id']}_data, {var['size']}, \"{var['hash']}\"}},\n")
        f.write("};\n\n#endif\n")

if __name__ == "__main__":
    print("--- Heuristic OS Mutation Pipeline ---")
    results = generate_variants()
    package_header(results)
    print(f"[SUCCESS] Generated {VARIANTS_COUNT} variants for CAmkES repository.")
